# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
        . ~/.bashrc
fi

# User specific environment and startup programs
export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"

export M2_HOME=/usr/local/apache-maven/apache-maven-3.9.9
export M2=$M2_HOME/bin
export PATH=$M2:$PATH