# github secret token for the onboarder-api-deploy.yaml
apiVersion: v1
kind: Secret
metadata:
  name: github-token
type: Opaque
data:
  token: "{{ lookup('env', 'REPO_CREATOR_TOKEN') | b64encode }}"

