apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: onboarder
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: "{{ lookup('env', 'ONBOARDER_INGRESS_HOST') }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: onboarder
                port:
                  number: 8080